export const CATEGORIES = [
  { id: 1, name: "프로젝트/사이드" },
  { id: 2, name: "자격증" },
  { id: 3, name: "CS - 기초" },
  { id: 4, name: "코딩테스트" },
  { id: 5, name: "취업 - 커리어" },
] as const

export type Category = (typeof CATEGORIES)[number]

export const LOCATIONS = [
  { id: 1, parentId: null, name: "서울" },
  { id: 2, parentId: null, name: "경기" },
  { id: 3, parentId: null, name: "인천" },
  { id: 4, parentId: null, name: "대전" },
  { id: 5, parentId: null, name: "세종" },
  { id: 6, parentId: null, name: "충남" },
  { id: 7, parentId: null, name: "충북" },
  { id: 8, parentId: null, name: "광주" },
  { id: 9, parentId: null, name: "전남" },
  { id: 10, parentId: null, name: "전북" },
  { id: 11, parentId: null, name: "대구" },
  { id: 12, parentId: null, name: "경북" },
  { id: 13, parentId: null, name: "부산" },
  { id: 14, parentId: null, name: "울산" },
  { id: 15, parentId: null, name: "경남" },
  { id: 16, parentId: null, name: "강원" },
  { id: 17, parentId: null, name: "제주" },
  { id: 18, parentId: 1, name: "강남구" },
  { id: 19, parentId: 1, name: "강동구" },
  { id: 20, parentId: 1, name: "강북구" },
  { id: 21, parentId: 1, name: "강서구" },
  { id: 22, parentId: 1, name: "관악구" },
  { id: 23, parentId: 1, name: "광진구" },
  { id: 24, parentId: 1, name: "구로구" },
  { id: 25, parentId: 1, name: "금천구" },
  { id: 26, parentId: 1, name: "노원구" },
  { id: 27, parentId: 1, name: "도봉구" },
  { id: 28, parentId: 1, name: "동대문구" },
  { id: 29, parentId: 1, name: "동작구" },
  { id: 30, parentId: 1, name: "마포구" },
  { id: 31, parentId: 1, name: "서대문구" },
  { id: 32, parentId: 1, name: "서초구" },
  { id: 33, parentId: 1, name: "성동구" },
  { id: 34, parentId: 1, name: "성북구" },
  { id: 35, parentId: 1, name: "송파구" },
  { id: 36, parentId: 1, name: "양천구" },
  { id: 37, parentId: 1, name: "영등포구" },
  { id: 38, parentId: 1, name: "용산구" },
  { id: 39, parentId: 1, name: "은평구" },
  { id: 40, parentId: 1, name: "종로구" },
  { id: 41, parentId: 1, name: "중구" },
  { id: 42, parentId: 1, name: "중랑구" },
  { id: 43, parentId: 2, name: "가평군" },
  { id: 44, parentId: 2, name: "고양시 덕양구" },
  { id: 45, parentId: 2, name: "고양시 일산동구" },
  { id: 46, parentId: 2, name: "고양시 일산서구" },
  { id: 47, parentId: 2, name: "과천시" },
  { id: 48, parentId: 2, name: "광명시" },
  { id: 49, parentId: 2, name: "광주시" },
  { id: 50, parentId: 2, name: "구리시" },
  { id: 51, parentId: 2, name: "군포시" },
  { id: 52, parentId: 2, name: "김포시" },
  { id: 53, parentId: 2, name: "남양주시" },
  { id: 54, parentId: 2, name: "동두천시" },
  { id: 55, parentId: 2, name: "부천시" },
  { id: 56, parentId: 2, name: "성남시 분당구" },
  { id: 57, parentId: 2, name: "성남시 수정구" },
  { id: 58, parentId: 2, name: "성남시 중원구" },
  { id: 59, parentId: 2, name: "수원시 권선구" },
  { id: 60, parentId: 2, name: "수원시 장안구" },
  { id: 61, parentId: 2, name: "수원시 팔달구" },
  { id: 62, parentId: 2, name: "수원시 영통구" },
  { id: 63, parentId: 2, name: "시흥시" },
  { id: 64, parentId: 2, name: "안산시 단원구" },
  { id: 65, parentId: 2, name: "안산시 상록구" },
  { id: 66, parentId: 2, name: "안성시" },
  { id: 67, parentId: 2, name: "안양시 동안구" },
  { id: 68, parentId: 2, name: "안양시 만안구" },
  { id: 69, parentId: 2, name: "양주시" },
  { id: 70, parentId: 2, name: "양평군" },
  { id: 71, parentId: 2, name: "여주시" },
  { id: 72, parentId: 2, name: "연천군" },
  { id: 73, parentId: 2, name: "오산시" },
  { id: 74, parentId: 2, name: "용인시 기흥구" },
  { id: 75, parentId: 2, name: "용인시 수지구" },
  { id: 76, parentId: 2, name: "용인시 처인구" },
  { id: 77, parentId: 2, name: "의왕시" },
  { id: 78, parentId: 2, name: "의정부시" },
  { id: 79, parentId: 2, name: "이천시" },
  { id: 80, parentId: 2, name: "파주시" },
  { id: 81, parentId: 2, name: "평택시" },
  { id: 82, parentId: 2, name: "포천시" },
  { id: 83, parentId: 2, name: "하남시" },
  { id: 84, parentId: 2, name: "화성시" },
  { id: 85, parentId: 3, name: "강화군" },
  { id: 86, parentId: 3, name: "계양구" },
  { id: 87, parentId: 3, name: "미추홀구" },
  { id: 88, parentId: 3, name: "남동구" },
  { id: 89, parentId: 3, name: "동구" },
  { id: 90, parentId: 3, name: "부평구" },
  { id: 91, parentId: 3, name: "서구" },
  { id: 92, parentId: 3, name: "연수구" },
  { id: 93, parentId: 3, name: "옹진군" },
  { id: 94, parentId: 3, name: "중구" },
  { id: 95, parentId: 4, name: "대덕구" },
  { id: 96, parentId: 4, name: "동구" },
  { id: 97, parentId: 4, name: "서구" },
  { id: 98, parentId: 4, name: "유성구" },
  { id: 99, parentId: 4, name: "중구" },
  { id: 100, parentId: 6, name: "공주시" },
  { id: 101, parentId: 6, name: "금산군" },
  { id: 102, parentId: 6, name: "논산시" },
  { id: 103, parentId: 6, name: "당진시" },
  { id: 104, parentId: 6, name: "보령시" },
  { id: 105, parentId: 6, name: "부여군" },
  { id: 106, parentId: 6, name: "서산시" },
  { id: 107, parentId: 6, name: "서천군" },
  { id: 108, parentId: 6, name: "아산시" },
  { id: 109, parentId: 6, name: "예산군" },
  { id: 110, parentId: 6, name: "천안시 동남구" },
  { id: 111, parentId: 6, name: "천안시 서북구" },
  { id: 112, parentId: 6, name: "청양군" },
  { id: 113, parentId: 6, name: "태안군" },
  { id: 114, parentId: 6, name: "홍성군" },
  { id: 115, parentId: 6, name: "계룡시" },
  { id: 116, parentId: 7, name: "괴산군" },
  { id: 117, parentId: 7, name: "단양군" },
  { id: 118, parentId: 7, name: "보은군" },
  { id: 119, parentId: 7, name: "영동군" },
  { id: 120, parentId: 7, name: "옥천군" },
  { id: 121, parentId: 7, name: "음성군" },
  { id: 122, parentId: 7, name: "제천시" },
  { id: 123, parentId: 7, name: "진천군" },
  { id: 124, parentId: 7, name: "청주시 청원구" },
  { id: 125, parentId: 7, name: "청주시 상당구" },
  { id: 126, parentId: 7, name: "청주시 서원구" },
  { id: 127, parentId: 7, name: "청주시 흥덕구" },
  { id: 128, parentId: 7, name: "충주시" },
  { id: 129, parentId: 7, name: "증평군" },
  { id: 130, parentId: 8, name: "광산구" },
  { id: 131, parentId: 8, name: "남구" },
  { id: 132, parentId: 8, name: "동구" },
  { id: 133, parentId: 8, name: "북구" },
  { id: 134, parentId: 8, name: "서구" },
  { id: 135, parentId: 9, name: "강진군" },
  { id: 136, parentId: 9, name: "고흥군" },
  { id: 137, parentId: 9, name: "곡성군" },
  { id: 138, parentId: 9, name: "광양시" },
  { id: 139, parentId: 9, name: "구례군" },
  { id: 140, parentId: 9, name: "나주시" },
  { id: 141, parentId: 9, name: "담양군" },
  { id: 142, parentId: 9, name: "목포시" },
  { id: 143, parentId: 9, name: "무안군" },
  { id: 144, parentId: 9, name: "보성군" },
  { id: 145, parentId: 9, name: "순천시" },
  { id: 146, parentId: 9, name: "신안군" },
  { id: 147, parentId: 9, name: "여수시" },
  { id: 148, parentId: 9, name: "영광군" },
  { id: 149, parentId: 9, name: "영암군" },
  { id: 150, parentId: 9, name: "완도군" },
  { id: 151, parentId: 9, name: "장성군" },
  { id: 152, parentId: 9, name: "장흥군" },
  { id: 153, parentId: 9, name: "진도군" },
  { id: 154, parentId: 9, name: "함평군" },
  { id: 155, parentId: 9, name: "해남군" },
  { id: 156, parentId: 9, name: "화순군" },
  { id: 157, parentId: 10, name: "고창군" },
  { id: 158, parentId: 10, name: "군산시" },
  { id: 159, parentId: 10, name: "김제시" },
  { id: 160, parentId: 10, name: "남원시" },
  { id: 161, parentId: 10, name: "무주군" },
  { id: 162, parentId: 10, name: "부안군" },
  { id: 163, parentId: 10, name: "순창군" },
  { id: 164, parentId: 10, name: "완주군" },
  { id: 165, parentId: 10, name: "익산시" },
  { id: 166, parentId: 10, name: "임실군" },
  { id: 167, parentId: 10, name: "장수군" },
  { id: 168, parentId: 10, name: "전주시 덕진구" },
  { id: 169, parentId: 10, name: "전주시 완산구" },
  { id: 170, parentId: 10, name: "정읍시" },
  { id: 171, parentId: 10, name: "진안군" },
  { id: 172, parentId: 11, name: "군위군" },
  { id: 173, parentId: 11, name: "남구" },
  { id: 174, parentId: 11, name: "달서구" },
  { id: 175, parentId: 11, name: "달성군" },
  { id: 176, parentId: 11, name: "동구" },
  { id: 177, parentId: 11, name: "북구" },
  { id: 178, parentId: 11, name: "서구" },
  { id: 179, parentId: 11, name: "수성구" },
  { id: 180, parentId: 11, name: "중구" },
  { id: 181, parentId: 12, name: "경산시" },
  { id: 182, parentId: 12, name: "경주시" },
  { id: 183, parentId: 12, name: "고령군" },
  { id: 184, parentId: 12, name: "구미시" },
  { id: 185, parentId: 12, name: "김천시" },
  { id: 186, parentId: 12, name: "문경시" },
  { id: 187, parentId: 12, name: "봉화군" },
  { id: 188, parentId: 12, name: "상주시" },
  { id: 189, parentId: 12, name: "성주군" },
  { id: 190, parentId: 12, name: "안동시" },
  { id: 191, parentId: 12, name: "영덕군" },
  { id: 192, parentId: 12, name: "영양군" },
  { id: 193, parentId: 12, name: "영주시" },
  { id: 194, parentId: 12, name: "영천시" },
  { id: 195, parentId: 12, name: "예천군" },
  { id: 196, parentId: 12, name: "울릉군" },
  { id: 197, parentId: 12, name: "울진군" },
  { id: 198, parentId: 12, name: "의성군" },
  { id: 199, parentId: 12, name: "청도군" },
  { id: 200, parentId: 12, name: "청송군" },
  { id: 201, parentId: 12, name: "칠곡군" },
  { id: 202, parentId: 12, name: "포항시 남구" },
  { id: 203, parentId: 12, name: "포항시 북구" },
  { id: 204, parentId: 13, name: "강서구" },
  { id: 205, parentId: 13, name: "금정구" },
  { id: 206, parentId: 13, name: "기장군" },
  { id: 207, parentId: 13, name: "남구" },
  { id: 208, parentId: 13, name: "동구" },
  { id: 209, parentId: 13, name: "동래구" },
  { id: 210, parentId: 13, name: "부산진구" },
  { id: 211, parentId: 13, name: "북구" },
  { id: 212, parentId: 13, name: "사상구" },
  { id: 213, parentId: 13, name: "사하구" },
  { id: 214, parentId: 13, name: "서구" },
  { id: 215, parentId: 13, name: "수영구" },
  { id: 216, parentId: 13, name: "연제구" },
  { id: 217, parentId: 13, name: "영도구" },
  { id: 218, parentId: 13, name: "중구" },
  { id: 219, parentId: 13, name: "해운대구" },
  { id: 220, parentId: 14, name: "남구" },
  { id: 221, parentId: 14, name: "동구" },
  { id: 222, parentId: 14, name: "북구" },
  { id: 223, parentId: 14, name: "울주군" },
  { id: 224, parentId: 14, name: "중구" },
  { id: 225, parentId: 15, name: "거제시" },
  { id: 226, parentId: 15, name: "거창군" },
  { id: 227, parentId: 15, name: "고성군" },
  { id: 228, parentId: 15, name: "김해시" },
  { id: 229, parentId: 15, name: "남해군" },
  { id: 230, parentId: 15, name: "밀양시" },
  { id: 231, parentId: 15, name: "사천시" },
  { id: 232, parentId: 15, name: "산청군" },
  { id: 233, parentId: 15, name: "양산시" },
  { id: 234, parentId: 15, name: "의령군" },
  { id: 235, parentId: 15, name: "진주시" },
  { id: 236, parentId: 15, name: "창녕군" },
  { id: 237, parentId: 15, name: "창원시 마산합포구" },
  { id: 238, parentId: 15, name: "창원시 마산회원구" },
  { id: 239, parentId: 15, name: "창원시 성산구" },
  { id: 240, parentId: 15, name: "창원시 의창구" },
  { id: 241, parentId: 15, name: "창원시 진해구" },
  { id: 242, parentId: 15, name: "통영시" },
  { id: 243, parentId: 15, name: "하동군" },
  { id: 244, parentId: 15, name: "함안군" },
  { id: 245, parentId: 15, name: "함양군" },
  { id: 246, parentId: 15, name: "합천군" },
  { id: 247, parentId: 16, name: "강릉시" },
  { id: 248, parentId: 16, name: "고성군" },
  { id: 249, parentId: 16, name: "동해시" },
  { id: 250, parentId: 16, name: "삼척시" },
  { id: 251, parentId: 16, name: "속초시" },
  { id: 252, parentId: 16, name: "양구군" },
  { id: 253, parentId: 16, name: "양양군" },
  { id: 254, parentId: 16, name: "영월군" },
  { id: 255, parentId: 16, name: "원주시" },
  { id: 256, parentId: 16, name: "인제군" },
  { id: 257, parentId: 16, name: "정선군" },
  { id: 258, parentId: 16, name: "철원군" },
  { id: 259, parentId: 16, name: "춘천시" },
  { id: 260, parentId: 16, name: "태백시" },
  { id: 261, parentId: 16, name: "평창군" },
  { id: 262, parentId: 16, name: "홍천군" },
  { id: 263, parentId: 16, name: "화천군" },
  { id: 264, parentId: 16, name: "횡성군" },
  { id: 265, parentId: 17, name: "서귀포시" },
  { id: 266, parentId: 17, name: "제주시" },
] as const

export type Location = (typeof LOCATIONS)[number]

// 시/도 목록 (parentId가 null인 것만)
export const getParentLocations = () =>
  LOCATIONS.filter((loc) => loc.parentId === null)

// 특정 시/도의 하위 구/군 목록
export const getChildLocations = (parentId: number) =>
  LOCATIONS.filter((loc) => loc.parentId === parentId)
